---
- hosts: myhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest
  - name: installing openjdk software
    yum:
      name: "java-1.8.0-openjdk-devel"
      state: present