---
- hosts: myhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest
  - name: installing python software
    yum:
      name: python
      state: present